wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689070080.934353
    t:
      1:
      - 1
      - 5
      - 6
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.10.9
      5: 0.15.5
      8:
      - 1
      - 5
